### PR TITLE
[WIP] Gulp task for running migration on startup

### PR DESCRIPTION
**Pull request by allenbrubaker**
Also references config.js for connection string.  There is an issue getting gulp to run both the db-migrate along with the normal build task.  

Relates to #4.

### CODE REVIEW

**Comment by allenbrubaker** [comment]
@williambogaiv  If you get any time, can you help me out with this.  I have tried and tried but cannot seem to spawn the child process to sufficiently run the pg-migrate up command.  It may be an issue with node or something I am just overlooking.  This relates to code in the migrate method of the root index.js file.

**Comment by williambogaiv** [comment]
@allenbrubaker, I modified the script to fix some syntax errors. You can try this if you want, but do not spend any substantial amount of time trying to get this to work. We can always manually run migrations on Heroku in order to get things to work.

```
diff --git a/src/index.js b/src/index.js
index 7de9c42..977a2ea 100644
--- a/src/index.js
+++ b/src/index.js
@@ -30,25 +30,34 @@ function main() {
                 layout: 'layout'
             })
         })
-        .error(message => console.log(message))
+        .catch(message => console.error(message))
 }
 
 function migrate() {
     // use the global connection string if found, else use the local one.
     var connectionString = process.env.DATABASE_URL || Config.connectionString
-    
-    var cmd = Path.join(__dirname, '..', 'node_modules', '.bin', 'pg-migrate');
-    console.log('Migrating db at: ' + connectionString
-                
+    var cmdSuffix = process.platform.match(/^win/i) !== null ? '.cmd' : '';
+    var cmd = Path.join(__dirname, '..', 'node_modules', '.bin', 'pg-migrate' + cmdSuffix);
+    console.log('Migrating db at: ' + connectionString);
+
     return new Promise((resolve, reject) => {
-        cp.spawn(cmd, ['up'], {
+        var process = cp.spawn(cmd, ['up'], {
             env: {
                 DATABASE_URL: connectionString
             }
-        })
-            .on('data', data => console.log(data.toString()))
-            .on('exit', resolve)
-            .on('error', reject)
+        });
+
+        process.stdout.on('data', data => console.log(data.toString()));
+        process.stderr.on('data', data => console.error(data.toString()));
+        process.on('exit', code => {
+            if (code === 0) {
+                resolve();
+            }
+            else {
+                reject('Migration process has exited with code: ' + code);
+            }
+        });
+        process.on('error', reject);
     })
 }
 
@@ -87,4 +96,4 @@ function outputRoutes(server) {
         .map(route => route.method + ' ' + route.path)
         .sort()
         .each(e => console.log(e))
-}
\ No newline at end of file
+}
```

**Comment by allenbrubaker** [comment]
I'm fairly certain I tried to run it with the .cmd suffix but still obtained same results, but I will try your changes out. It would be nice to get this to work so developers don't need to know to add DATABASE_URL to environment variables and manually migrate each time :/.

**Comment by williambogaiv** [comment]
@allenbrubaker, why was the title changed to remove the WIP-prefix? Are you still working on getting the migration task running? You'll need to rebase with master since there is a merge-conflict with your branch as-is.

**Comment by allenbrubaker** [comment]
Unable to solve problem with child process inability to spawn pg-migrate script.

**Pull request closed without merging**
