### PR TITLE
Siren integration with web api

### PR DESCRIPTION
**Pull request by allenbrubaker**
Siren integration with web api.  Currently mocking terms since db logic isn't complete yet.

### CODE REVIEW

**Comment by allenbrubaker** [comment]
Ok.. just updated it.  I really need to get kdiff working somehow... because I miss one or two little lines between two globs of differences.

**Comment by williambogaiv** [comment]
:smiley: tests are passing!

**Comment by allenbrubaker** [comment]
Woooot nice team work!! :+1:

**Comment by allenbrubaker** [comment]
Is there a way to see the number of passing tests on here instead of just 'the travis ci build passed'?  It would be cool to see that information.

**Comment by williambogaiv** [comment]
@allenbrubaker there are quite a few breaking app. changes in this PR related to web-client view URIs. Can this be merged as-is?

**Comment by allenbrubaker** [comment]
Calling the following code by navigating to https://localhost:3000/api/terms/1:  
```
var term = new Term(1, 'FMO', 'Field Marketing Organization')
term.testApi = new TestApi(3, 100, 'string', -5.5)
var siren = new Siren(term)
return siren.json
```

Returns this siren+json:

```
{
    "class": ["Term"],
    "rel": ["Term"],
    "properties": {
        "id": 1,
        "term": "FMO",
        "definition": "Field Marketing Organization"
    },
    "entities": [{
        "class": ["tags", "[]"],
        "rel": ["Term.[]"],
        "href": "https://localhost:3000/api/terms/1/tags"
    }, {
        "class": ["testApi", "TestApi"],
        "rel": ["Term.TestApi"],
        "properties": {
            "id": 3,
            "parmNumber": 100,
            "parmString": "string",
            "parmFloat": -5.5
        },
        "entities": [],
        "links": [{
            "rel": ["self"],
            "href": "https://localhost:3000/api/testApi/3"
        }],
        "actions": [{
            "name": "postMethod",
            "title": "postMethod",
            "href": "https://localhost:3000/api/postUrl2",
            "method": "POST",
            "fields": []
        }, {
            "name": "putMethod",
            "title": "putMethod",
            "href": "https://localhost:3000/api/putUrl2",
            "method": "PUT",
            "fields": [{
                "name": "a",
                "type": "Function"
            }]
        }, {
            "name": "patchMethod",
            "title": "patchMethod",
            "href": "https://localhost:3000/api/patchUrl2",
            "method": "PATCH",
            "fields": [{
                "name": "b",
                "type": "Function"
            }, {
                "name": "c",
                "type": "Function"
            }]
        }, {
            "name": "deleteMethod",
            "title": "deleteMethod",
            "href": "https://localhost:3000/api/deleteUrl2",
            "method": "DELETE",
            "fields": [{
                "name": "d",
                "type": "Function"
            }, {
                "name": "e",
                "type": "Function"
            }, {
                "name": "f",
                "type": "Function"
            }]
        }]
    }],
    "links": [{
        "rel": ["self"],
        "href": "https://localhost:3000/api/terms/1"
    }],
    "actions": [{
        "name": "postMethod",
        "title": "postMethod",
        "href": "https://localhost:3000/api/postUrl",
        "method": "POST",
        "fields": []
    }, {
        "name": "putMethod",
        "title": "putMethod",
        "href": "https://localhost:3000/api/putUrl",
        "method": "PUT",
        "fields": [{
            "name": "a",
            "type": "Function"
        }]
    }, {
        "name": "patchMethod",
        "title": "patchMethod",
        "href": "https://localhost:3000/api/patchUrl",
        "method": "PATCH",
        "fields": [{
            "name": "b",
            "type": "Function"
        }, {
            "name": "c",
            "type": "Function"
        }]
    }, {
        "name": "deleteMethod",
        "title": "deleteMethod",
        "href": "https://localhost:3000/api/deleteUrl",
        "method": "DELETE",
        "fields": [{
            "name": "d",
            "type": "Function"
        }, {
            "name": "e",
            "type": "Function"
        }, {
            "name": "f",
            "type": "Function"
        }]
    }]
}
```

Navigating to the list of all the terms at : https://localhost:3000/api/terms:

```
[{
    "class": ["Term"],
    "rel": ["Term"],
    "properties": {
        "id": 1,
        "term": "FMO",
        "definition": "Field Marketing Organization"
    },
    "entities": [{
        "class": ["tags", "[]"],
        "rel": ["Term.[]"],
        "href": "https://localhost:3000/api/terms/1/tags"
    }, {
        "class": ["testApi", "TestApi"],
        "rel": ["Term.TestApi"],
        "properties": {
            "id": 3,
            "parmNumber": 100,
            "parmString": "string",
            "parmFloat": -5.5
        },
        "entities": [],
        "links": [{
            "rel": ["self"],
            "href": "https://localhost:3000/api/testApi/3"
        }],
        "actions": [{
            "name": "postMethod",
            "title": "postMethod",
            "href": "https://localhost:3000/api/postUrl2",
            "method": "POST",
            "fields": []
        }, {
            "name": "putMethod",
            "title": "putMethod",
            "href": "https://localhost:3000/api/putUrl2",
            "method": "PUT",
            "fields": [{
                "name": "a",
                "type": "Function"
            }]
        }, {
            "name": "patchMethod",
            "title": "patchMethod",
            "href": "https://localhost:3000/api/patchUrl2",
            "method": "PATCH",
            "fields": [{
                "name": "b",
                "type": "Function"
            }, {
                "name": "c",
                "type": "Function"
            }]
        }, {
            "name": "deleteMethod",
            "title": "deleteMethod",
            "href": "https://localhost:3000/api/deleteUrl2",
            "method": "DELETE",
            "fields": [{
                "name": "d",
                "type": "Function"
            }, {
                "name": "e",
                "type": "Function"
            }, {
                "name": "f",
                "type": "Function"
            }]
        }]
    }],
    "links": [{
        "rel": ["self"],
        "href": "https://localhost:3000/api/terms/1"
    }],
    "actions": [{
        "name": "postMethod",
        "title": "postMethod",
        "href": "https://localhost:3000/api/postUrl",
        "method": "POST",
        "fields": []
    }, {
        "name": "putMethod",
        "title": "putMethod",
        "href": "https://localhost:3000/api/putUrl",
        "method": "PUT",
        "fields": [{
            "name": "a",
            "type": "Function"
        }]
    }, {
        "name": "patchMethod",
        "title": "patchMethod",
        "href": "https://localhost:3000/api/patchUrl",
        "method": "PATCH",
        "fields": [{
            "name": "b",
            "type": "Function"
        }, {
            "name": "c",
            "type": "Function"
        }]
    }, {
        "name": "deleteMethod",
        "title": "deleteMethod",
        "href": "https://localhost:3000/api/deleteUrl",
        "method": "DELETE",
        "fields": [{
            "name": "d",
            "type": "Function"
        }, {
            "name": "e",
            "type": "Function"
        }, {
            "name": "f",
            "type": "Function"
        }]
    }]
}, {
    "class": ["Term"],
    "rel": ["Term"],
    "properties": {
        "id": 2,
        "term": "CMS",
        "definition": "Center for Medicare and Medicaid Services"
    },
    "entities": [{
        "class": ["tags", "[]"],
        "rel": ["Term.[]"],
        "href": "https://localhost:3000/api/terms/2/tags"
    }],
    "links": [{
        "rel": ["self"],
        "href": "https://localhost:3000/api/terms/2"
    }],
    "actions": [{
        "name": "postMethod",
        "title": "postMethod",
        "href": "https://localhost:3000/api/postUrl",
        "method": "POST",
        "fields": []
    }, {
        "name": "putMethod",
        "title": "putMethod",
        "href": "https://localhost:3000/api/putUrl",
        "method": "PUT",
        "fields": [{
            "name": "a",
            "type": "Function"
        }]
    }, {
        "name": "patchMethod",
        "title": "patchMethod",
        "href": "https://localhost:3000/api/patchUrl",
        "method": "PATCH",
        "fields": [{
            "name": "b",
            "type": "Function"
        }, {
            "name": "c",
            "type": "Function"
        }]
    }, {
        "name": "deleteMethod",
        "title": "deleteMethod",
        "href": "https://localhost:3000/api/deleteUrl",
        "method": "DELETE",
        "fields": [{
            "name": "d",
            "type": "Function"
        }, {
            "name": "e",
            "type": "Function"
        }, {
            "name": "f",
            "type": "Function"
        }]
    }]
}, {
    "class": ["Term"],
    "rel": ["Term"],
    "properties": {
        "id": 3,
        "term": "NIPR",
        "definition": "National Insurance Producer Registry"
    },
    "entities": [{
        "class": ["tags", "[]"],
        "rel": ["Term.[]"],
        "href": "https://localhost:3000/api/terms/3/tags"
    }],
    "links": [{
        "rel": ["self"],
        "href": "https://localhost:3000/api/terms/3"
    }],
    "actions": [{
        "name": "postMethod",
        "title": "postMethod",
        "href": "https://localhost:3000/api/postUrl",
        "method": "POST",
        "fields": []
    }, {
        "name": "putMethod",
        "title": "putMethod",
        "href": "https://localhost:3000/api/putUrl",
        "method": "PUT",
        "fields": [{
            "name": "a",
            "type": "Function"
        }]
    }, {
        "name": "patchMethod",
        "title": "patchMethod",
        "href": "https://localhost:3000/api/patchUrl",
        "method": "PATCH",
        "fields": [{
            "name": "b",
            "type": "Function"
        }, {
            "name": "c",
            "type": "Function"
        }]
    }, {
        "name": "deleteMethod",
        "title": "deleteMethod",
        "href": "https://localhost:3000/api/deleteUrl",
        "method": "DELETE",
        "fields": [{
            "name": "d",
            "type": "Function"
        }, {
            "name": "e",
            "type": "Function"
        }, {
            "name": "f",
            "type": "Function"
        }]
    }]
}, {
    "class": ["Term"],
    "rel": ["Term"],
    "properties": {
        "id": 4,
        "term": "NPN",
        "definition": "National Producer Number"
    },
    "entities": [{
        "class": ["tags", "[]"],
        "rel": ["Term.[]"],
        "href": "https://localhost:3000/api/terms/4/tags"
    }],
    "links": [{
        "rel": ["self"],
        "href": "https://localhost:3000/api/terms/4"
    }],
    "actions": [{
        "name": "postMethod",
        "title": "postMethod",
        "href": "https://localhost:3000/api/postUrl",
        "method": "POST",
        "fields": []
    }, {
        "name": "putMethod",
        "title": "putMethod",
        "href": "https://localhost:3000/api/putUrl",
        "method": "PUT",
        "fields": [{
            "name": "a",
            "type": "Function"
        }]
    }, {
        "name": "patchMethod",
        "title": "patchMethod",
        "href": "https://localhost:3000/api/patchUrl",
        "method": "PATCH",
        "fields": [{
            "name": "b",
            "type": "Function"
        }, {
            "name": "c",
            "type": "Function"
        }]
    }, {
        "name": "deleteMethod",
        "title": "deleteMethod",
        "href": "https://localhost:3000/api/deleteUrl",
        "method": "DELETE",
        "fields": [{
            "name": "d",
            "type": "Function"
        }, {
            "name": "e",
            "type": "Function"
        }, {
            "name": "f",
            "type": "Function"
        }]
    }]
}, {
    "class": ["Term"],
    "rel": ["Term"],
    "properties": {
        "id": 5,
        "term": "NAIC",
        "definition": "National Association of Insurance Commissioners"
    },
    "entities": [{
        "class": ["tags", "[]"],
        "rel": ["Term.[]"],
        "href": "https://localhost:3000/api/terms/5/tags"
    }],
    "links": [{
        "rel": ["self"],
        "href": "https://localhost:3000/api/terms/5"
    }],
    "actions": [{
        "name": "postMethod",
        "title": "postMethod",
        "href": "https://localhost:3000/api/postUrl",
        "method": "POST",
        "fields": []
    }, {
        "name": "putMethod",
        "title": "putMethod",
        "href": "https://localhost:3000/api/putUrl",
        "method": "PUT",
        "fields": [{
            "name": "a",
            "type": "Function"
        }]
    }, {
        "name": "patchMethod",
        "title": "patchMethod",
        "href": "https://localhost:3000/api/patchUrl",
        "method": "PATCH",
        "fields": [{
            "name": "b",
            "type": "Function"
        }, {
            "name": "c",
            "type": "Function"
        }]
    }, {
        "name": "deleteMethod",
        "title": "deleteMethod",
        "href": "https://localhost:3000/api/deleteUrl",
        "method": "DELETE",
        "fields": [{
            "name": "d",
            "type": "Function"
        }, {
            "name": "e",
            "type": "Function"
        }, {
            "name": "f",
            "type": "Function"
        }]
    }]
}]
```

**Pull request merged**
